export const SKILL_LIST = [
  {
    id: 1,
    name: 'Apache',
    designation: 'Apache',
    image: './svgl/apache.svg',
  },
  {
    id: 2,
    name: 'Claude Code',
    designation: 'Claude Code',
    image: './svgl/claude-ai-icon.svg',
  },
  {
    id: 3,
    name: 'Docker',
    designation: 'Docker',
    image: './svgl/docker.svg',
  },
  {
    id: 4,
    name: 'ESLint',
    designation: 'ESLint',
    image: './svgl/ESLint_light.svg',
  },
  {
    id: 5,
    name: 'Git',
    designation: 'Git',
    image: './svgl/git.svg',
  },
  {
    id: 6,
    name: 'Github',
    designation: 'Github',
    image: './svgl/github_light.svg',
  },
  {
    id: 7,
    name: 'Gitlab',
    designation: 'Gitlab',
    image: './svgl/gitlab.svg',
  },
  {
    id: 8,
    name: 'Kubernetes',
    designation: 'Kubernetes',
    image: './svgl/kubernetes.svg',
  },
  {
    id: 9,
    name: 'Linux',
    designation: 'Linux',
    image: './svgl/linux.svg',
  },
  {
    id: 10,
    name: 'MongoDB',
    designation: 'MongoDB',
    image: './svgl/MongoDB_dark.svg',
  },
  {
    id: 11,
    name: 'n8n',
    designation: 'n8n',
    image: './svgl/n8n.svg',
  },
  {
    id: 12,
    name: 'NextJS',
    designation: 'NextJs',
    image: './svgl/nextjs_icon_dark.svg',
  },
  {
    id: 13,
    name: 'NGINX',
    designation: 'NGINX',
    image: './svgl/nginx.svg',
  },
  {
    id: 14,
    name: 'Node.js',
    designation: 'Node.js',
    image: './svgl/nodejs.svg',
  },
  {
    id: 15,
    name: 'PostgreSQL',
    designation: 'PostgreSQL',
    image: './svgl/postgresql.svg',
  },
  {
    id: 16,
    name: 'Prettier',
    designation: 'Prettier',
    image: './svgl/Prettier_light.svg',
  },
  {
    id: 17,
    name: 'Python',
    designation: 'Python',
    image: './svgl/python.svg',
  },
  {
    id: 18,
    name: 'Radix UI',
    designation: 'Radix UI',
    image: './svgl/Radix_UI_light.svg',
  },
  {
    id: 19,
    name: 'Sentry',
    designation: 'Sentry',
    image: './svgl/sentry.svg',
  },
  {
    id: 20,
    name: 'Shadcn',
    designation: 'Shadcn',
    image: './svgl/ui_light.svg',
  },
  {
    id: 21,
    name: 'Shell',
    designation: 'Shell',
    image: './svgl/powershell.svg',
  },
  {
    id: 22,
    name: 'Solidity',
    designation: 'Solidity',
    image: './svgl/solidity.svg',
  },
  {
    id: 23,
    name: 'Swagger',
    designation: 'Swagger',
    image: './svgl/swagger.svg',
  },
  {
    id: 24,
    name: 'TailwindCSS',
    designation: 'TailwindCSS',
    image: './svgl/tailwindcss.svg',
  },
  {
    id: 25,
    name: 'Terraform',
    designation: 'Terraform',
    image: './svgl/terraform.svg',
  },
  {
    id: 26,
    name: 'Typescript',
    designation: 'Typescript',
    image: './svgl/typescript.svg',
  },
  {
    id: 27,
    name: 'Ubuntu',
    designation: 'Ubuntu',
    image: './svgl/ubuntu.svg',
  },
]
